language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: ree
    - rvm: jruby-18mode
  fast_finish: true
